language: android
before_install:
    - chmod +x gradlew
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support
    - extra-android-m2repository
jdk:
    - oraclejdk8

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-17
