language: android
before_install:
    - chmod +x gradlew
android:
  components:
    - build-tools-24.0.1
    - tools
    - tools
    - android-24
    - extra-android-support
    - extra-android-m2repository
